development:
  adapter: postgresql
  encoding: unicode
  database: peoplespark_development
  pool: 5
  username: peoplespark
  password: peoplespark_dev

test:
  adapter: postgresql
  encoding: unicode
  database: peoplespark_test
  pool: 5
  username: peoplespark
  password: peoplespark_dev

